### ISSUE TITLE
Uncoordinated Checkpoints

### ISSUE THREAD

**Issue by bethven** [vlmarkov/Fault-Tolerance-Library#1]
Hi,
I would like to know if with 54markov/Fault-Tolerance-Library you can run Uncoordinated Checkpoints with MPI applications.
I need to do this and I do not know with what I can do it.
Thank you very much.

**Comment by vlmarkov** [comment]
Good time of day)
No, my current implementation supports only coordinated (in some way)
approach. (because i save data to file in the end of each iteration)
For example: But if your MPI-app don't call MPI_Barrier after and before
save_checkpoint() function - so this aproach could be uncoordinated...
I hope this example can help you to solve your problem

**Comment by bethven** [comment]
hello, thank you very much for your quick response.
I need to make an MPI program could be one of the NAS an uncoordinated checkpoint, but I do not know what tools I should use to do it.
I have worked with the DMTCP library to do a coodinated checkpoint, but now I need to do an uncoodinated checkpoint using any tool.
But I am a bit confused about the steps I must take to achieve it.
thank you very much.

**Comment by vlmarkov** [comment]
One solution is you could try to use Fenix (links to pdf and source bellow)
http://prod.sandia.gov/techlib/access-control.cgi/2016/1610522.pdf
https://pdfs.semanticscholar.org/presentation/ab31/45ac50956a9072e735e840871071cac2c468.pdf
https://github.com/epizon-project/Fenix
The other solution is, to write your own user-level checkpoint lib (that
only do is save you data "void save_fun(void *data, size_t n_bytes)").
And as i undesrstand if your mpi-app and mpi-processes don't want to call
sync mpi-primitives each time before and after save_func() that will be
uncoodinated aproach.
